title: Fullstack Developer
author: GitHub User
email: tgollaher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 A display of frontend and backend web developemnt projects

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
